apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscale-entregas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aplicacion-entregas
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50